### ISSUE TITLE
TEAM4 - vuln1 issue

### ISSUE THREAD

**Issue by ChefYeum** [PecentZero/GIT_TEAM_HTML#25]
-----BEGIN PGP MESSAGE-----

hQGMA72jSERawbZeAQwAtvuPvnVyXP9m1K0QbkpQo/2w308V1nBomkXh2O10fz9Y
G0WhaQzsmp4kGgwNX7Rg8B7GM57WKqDQAA5qpF/sILIaWD59KIQxmh8uOAUC7uQg
3s993ZoJDx7gNvtQCSelXEW/aj48xJAIrcVsTHnEIjIWd8qYl3qsSEniGJUGsE3H
FCg+1aF+bk4OduXQRpOBKV5J/I04M2vgGr9+8aG2XkfvOJkwjzeTGMugr+OFL6rX
bL5iUWNWPqHkf1+2lf5v4eNVOtVi/Rtw51bY/HzoTgHL144a3YmK+Yfea1f8fdQM
6vzj51iFefGC5nHrMXW2E5zAqrOu+76kBiWbnX1Eaa9/3/fNDFMxay20JQACib+P
HnyeXGIjS1oky+QGfRiBhHaSjbYPAQfFIu0NjL9atphQF8/fb//lH3rNdJBQQQ6G
CklYdeOkG3pH73aUg3B2gAzW/Gr7owVZ6tgBvVM06sEJUyhuJB8Kqn7USOjtey8y
+uJqbYqBVUUU9l0fwCK60sC4AdFa9ukk/baM5z1p//el/eg5WCzd76GMaafe5EbS
uXb2VtIjdP+iejo8bHtKUpg9b7vh7Ko0hR9vOag4Sup/zUSmndwXkjITSmrlHK7l
IWSfCh+tZnQ1Itg5l/LYLovwDTQ3ZbrBac1sy+L30yySNPNCLi/SgOST29m0k5MR
xz8zb0e23itMgDHocmmVwEGlChCMklfctk+B5/e8UzR1Am5U/U2zFs9zHkBEZkPf
cb9dA09ueLd7okHAqY+pR92Mg1pBd1PBeK9H+3mUH6kGUugGFm1I9B3ahvjZ1Ig0
DOgUY7mE215u7vhpwF5r34ig5lUNEZs/7vuPpXD+ioGz81CIO7EywlgLA2aaOJSD
akpwW7Y2pFjB7oKFL3dmuBd0DweC+dCh+LFwg8VzcUEh+OlywACO9GN8vjMO/wEE
87LeefgYkgbLFSu0SDnpuApyo4syc9QVjV0H5EKkaZdz8XTIlb/SQO5N2gkpd2aT
evh4uO1OY4hWRQ==
=LD88
-----END PGP MESSAGE-----

**Comment by foreverals2002** [comment]
Wrong Encryption (It seems that the text is encrypted with TEAM4's pub_key, so we cannot decrypt it)

**Comment by COSE451-TA** [comment]
@ChefYeum, @foreverals2002 
Since GitCTF has ended, we will close this issue.
